---
- name: Pull Calculator App from Docker Hub
  hosts: myhosts
  tasks: 
   - name: Install Docker
     apt:
       name: docker.io
       state: present

   - name: Pull the latest Docker image
     community.docker.docker_image:
       name: "aie007/calc:latest"
       source: pull

   - name: Stop and remove existing container if any
     community.docker.docker_container:
       name: calc
       state: absent	

   - name: Run new container
       community.docker.docker_container:
         name: calc
	 image: aie007/calc:latest
         state: started
	 restart_policy: always
	 interactive: true
